### ISSUE TITLE
Definição de padrões para o projeto

### ISSUE THREAD

**Issue by xmnlab** [somosprte/Hermes#4]
Para todo projeto, principalmente projetos open source, é fundamental utilizar padronizações.

Gostaria de propor a utilização de um template de projeto:

https://github.com/audreyr/cookiecutter-pypackage

Para os testes poderiamos utilizar o pytest (http://pythontesting.net/transcripts/2-pytest-vs-unittest-vs-nose/)

E podemos adicionar a verificação do pep8 também para que o código esteja conforme as especificações (https://www.python.org/dev/peps/pep-0008/) . Podemos fazer isso com a lib pycodestyle (https://pypi.python.org/pypi/pycodestyle)

**Comment by pedrorenan** [comment]
Excelentes sugestões @xmnlab 
Sugiro que usemos BDD e podemos fazer isso usando o pytest https://pypi.python.org/pypi/pytest-bdd

**Comment by xmnlab** [comment]
show ;)

**Comment by xmnlab** [comment]
@pedrorenan poderiamos mudar o nome da pasta docs do projeto (que está vinculado a página)?

digo isso porque a pasta padrão para a documentação de código (com readthedocs) também usa uma pasta chamada docs .... 

eu poderia trocar essa pasta por outro nome .. mas iria ficar confuso ... me parece mais lógico colocar o nome da pasta para algo como web ou site ... ou até melhor .. criar um projeto separado para ele.

o que opinas?
